### ISSUE TITLE
Document and Tests Configuration API

### ISSUE THREAD

**Issue by Y2Kwastaken** [PineappleDevelopmentGroup/Pineapple#27]
The current Configuration API is good, but it still needs Documentation and Tests to ensure it doesn't fail if changes are made at a later date

**Comment by The-Epic** [comment]
added in [bb89706640e386dff8f873a6db1e15abcc19a463](https://github.com/PineappleDevelopmentGroup/Pineapple/commit/bb89706640e386dff8f873a6db1e15abcc19a463) & [d2dc52fecdd4440ea616ab154264c2ba9d8a1a6b](https://github.com/PineappleDevelopmentGroup/Pineapple/commit/d2dc52fecdd4440ea616ab154264c2ba9d8a1a6b)
